### ISSUE TITLE
IDEA download times out too easily

### ISSUE THREAD

**Issue by a1russell** [gini/puppet-idea#4]
Would you please increase the timeout for the IDEA download? I find this timing out quite often unless I am on an extremely good connection.

**Comment by dkerwin** [comment]
Hi,

i just pushed a new version to the forge. It has been moved to the gini namespace and can be found here: http://forge.puppetlabs.com/gini/idea (v.0.2.0).
Unfortunately it's not possible to remove the old module from the smarchive namespace on the forge. Please update your setup accordingly.

Cheers!
Daniel

**Comment by lidonis** [comment]
This broke ultimate version because it does not use timeout.
